@base = http://localhost:4000

GET {{base}}/graph

###

GET {{base}}/ui

###

POST {{base}}/graph
content-type: application/json

[{
  "caller": "A",
  "callee": "B",
  "metrics": {
    "duration": 12,
    "errored": true,
    "timestamp": {{$timestamp}}000000
  }
}]

###

POST {{base}}/graph
content-type: application/json

[{
  "caller": "A",
  "callee": "C",
  "metrics": {
    "duration": 12,
    "errored": true,
    "timestamp": {{$timestamp}}000000
  }
}]

###

POST {{base}}/graph
content-type: application/json

[{
  "caller": "B",
  "callee": "C",
  "metrics": {
    "duration": 12,
    "errored": true,
    "timestamp": {{$timestamp}}000000
  }
}]

###

POST {{base}}/graph
content-type: application/json

[{
  "callee": "D",
  "metrics": {
    "duration": 12,
    "errored": true,
    "timestamp": {{$timestamp}}000000
  }
}]

###

POST {{base}}/graph
content-type: application/json

[{
  "callee": "E",
  "metrics": {
    "duration": 12,
    "errored": true,
    "timestamp": {{$timestamp}}000000
  }
}]

###

POST {{base}}/graph/search
Content-Type: application/json

{"component": "A"}

###

PATCH {{base}}/graph/components/status
Content-Type: application/json

{
  "component": "J",
  "status": "CONFIRMED"
}

###

PATCH {{base}}/graph/components/status
Content-Type: application/json

{
  "component": "H",
  "status": "NORMAL"
}


###

DELETE {{base}}/graph
