# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.6.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run: pwd && ls

      # Download and cache dependencies
      - restore_cache:
          keys:
            - &root_cache root-v1-deps-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - root--v1-deps-
      - restore_cache:
          keys:
            - &ingress_cache ingress-v1-deps-{{ checksum "ingress/package.json" }}
            - ingress-v1-deps-
      - restore_cache:
          keys:
            - &helpers_cache helpers-v1-deps-{{ checksum "helpers/package.json" }}
            - helpers-v1-deps-
      - restore_cache:
          keys:
            - &dependency_detector_cache dependency_detector-v1-deps-{{ checksum "dependency-detector/package.json" }}
            - dependency_detector-v1-deps-
      - restore_cache:
          keys:
            - &graph_service_cache graph_service-v1-deps-{{ checksum "graph-service/package.json" }}
            - graph_service-v1-deps-
      - restore_cache:
          keys:
            - &anomaly_detector_cache anomaly_detector-v1-deps-{{ checksum "anomaly-detector/package.json" }}
            - anomaly_detector-v1-deps-

      - run: npm ci && npm run ci:install-all-projects

      - save_cache:
          key: *root_cache
          paths:
            - node_modules
      - save_cache:
          key: *ingress_cache
          paths:
            - ingress/node_modules
      - save_cache:
          key: *helpers_cache
          paths:
            - helpers/node_modules
      - save_cache:
          key: *dependency_detector_cache
          paths:
            - dependency-detector/node_modules
      - save_cache:
          key: *graph_service_cache
          paths:
            - graph-service/node_modules
      - save_cache:
          key: *anomaly_detector_cache
          paths:
            - anomaly-detector/node_modules

      # run tests!
      - run: npm test
