version: "3.7"

x-base-environment: &base-environment
  INGRESS_HOST: ${NC_HOST:-host.docker.internal}
  INGRESS_PORT: ${NC_PORT:-3000}

x-base-service: &base-service
  build:
    context: .
  volumes:
    - "./routers:/project/app/routers"
    - "./nodemon.json:/project/app/nodemon.json"
    - "./tsconfig.json:/project/app/tsconfig.json"
    - "./recorder.ts:/project/app/recorder.ts"
    - "./server.ts:/project/app/server.ts"
    - "./servicesFetch.ts:/project/app/servicesFetch.ts"

services:
  xapi:
    <<: *base-service
    links:
      - redis
      - iam
    ports:
      - "7000:80"
    environment:
      <<: *base-environment
      NAME: xapi

  iam:
    <<: *base-service
    links:
      - postgres
    environment:
      <<: *base-environment
      NAME: iam

  inventory:
    <<: *base-service
    environment:
      <<: *base-environment
      NAME: inventory

  billing:
    <<: *base-service
    environment:
      <<: *base-environment
      NAME: billing

  payments:
    <<: *base-service
    environment:
      <<: *base-environment
      NAME: payments

  redis:
    image: redis

  postgres:
    image: postgres:11
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  jmeter:
    image: justb4/jmeter
    volumes:
      - "./jmeter-plan.jmx:/plan.jmx"
    command: -n -t /plan.jmx -l /results.jtl
    depends_on:
      - xapi
    # entrypoint: /bin/bash
